# Generated by Django 3.1.4 on 2021-04-06 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'manager'), ('user', 'user'), ('partner', 'partner')], default='user', max_length=20)),
                ('double_pwd', models.CharField(default='123456', max_length=6)),
                ('verify_type', models.CharField(default='1', max_length=10)),
                ('user_type', models.CharField(default='STUDENT', max_length=20)),
                ('balance_amt', models.IntegerField(default=0)),
                ('point_amt', models.IntegerField(default=0)),
                ('profile_img', models.ImageField(blank=True, default='human.png', null=True, upload_to='static/profiles')),
                ('profile_url', models.CharField(db_column='profile_url', default='', max_length=1024, null=True)),
                ('qrcode_img', models.ImageField(blank=True, default='qr_user.png', null=True, upload_to='static/qrcode')),
                ('qrcode_url', models.CharField(db_column='qrcode_url', default='', max_length=1024, null=True)),
                ('usage_flag', models.CharField(default='1', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
