# Generated by Django 3.2.3 on 2021-06-18 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souser', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='logaction',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='logstatus',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='logtime',
            field=models.DateTimeField(db_column='logtime', default=datetime.datetime(2021, 6, 18, 16, 10, 20, 219665), null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
